brew "bat"
brew "binutils"
brew "binwalk"
brew "btop"
brew "clang-format"
brew "cmake"
brew "fd"
brew "fish"
brew "fzf"
brew "gcc"
brew "gdb"
brew "git-absorb"
brew "gitui"
brew "hashcat"
brew "lld"
brew "llvm"
brew "magic-wormhole"
brew "make"
brew "mdcat"
brew "neovim"
brew "qemu"
brew "ripgrep"
brew "rust-analyzer"
brew "rustup"
brew "sequoia-sq"
brew "shellcheck"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "uv"
brew "yara-x"
brew "zoxide"

uv "pwntools"
uv "ruff"
uv "ty"

cargo "gratz", source: "https://github.com/miikaoskari/gratz"
cargo "mkcdoc", source: "https://github.com/miikaoskari/mkcdoc"

tap "pwndbg/tap"
cask "pwndbg/tap/pwndbg-gdb", trusted: true

cask "claude-code"
cask "zed"
