#!/bin/bash
set -euxo pipefail

NONINTERACTIVE=1 scripts/brew

brew bundle

# fish stuff
chsh -s /home/linuxbrew/.linuxbrew/bin/fish
ln -sfn "$(pwd)/fish/functions" "$HOME/.config/fish/functions
fish -c 'fzf --fish | source'
